# Generated by Django 5.1.2 on 2024-11-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('ID_Admin', models.AutoField(primary_key=True, serialize=False)),
                ('Mail', models.EmailField(max_length=255, unique=True, verbose_name="Email de l'Administrateur")),
                ('mdp', models.CharField(max_length=255, verbose_name='Mot de Passe')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='AppelOffre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField()),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('profil', models.CharField(max_length=50)),
                ('tjm_min', models.CharField(max_length=50)),
                ('tjm_max', models.CharField(max_length=50)),
                ('date_publication', models.DateField(max_length=255)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'appeloffre',
            },
        ),
        migrations.CreateModel(
            name='Bondecommande',
            fields=[
                ('id_bdc', models.AutoField(primary_key=True, serialize=False)),
                ('candidature_id', models.IntegerField()),
                ('numero_bdc', models.CharField(blank=True, max_length=50, null=True)),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('montant_total', models.FloatField()),
                ('statut', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bondecommande',
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id_cd', models.AutoField(primary_key=True, serialize=False)),
                ('AO_id', models.IntegerField()),
                ('esn_id', models.IntegerField()),
                ('responsable_compte', models.CharField(blank=True, max_length=255, null=True)),
                ('id_consultant', models.IntegerField()),
                ('date_candidature', models.DateField()),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Sélectionnée', 'Sélectionnée'), ('Rejetée', 'Rejetée')], max_length=20)),
                ('tjm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_disponibilite', models.DateField()),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'candidature',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ID_clt', models.AutoField(primary_key=True, serialize=False)),
                ('raison_sociale', models.CharField(max_length=255, verbose_name='Raison Sociale')),
                ('siret', models.CharField(max_length=14, unique=True, verbose_name='Numéro SIRET')),
                ('rce', models.CharField(blank=True, max_length=255, null=True, verbose_name='RCE')),
                ('pays', models.CharField(max_length=100, verbose_name='Pays')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('cp', models.CharField(max_length=10, verbose_name='CP')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Province')),
                ('mail_contact', models.EmailField(max_length=254, unique=True, verbose_name='Email de Contact')),
                ('password', models.CharField(max_length=255, verbose_name='Mot de Passe')),
                ('tel_contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone de Contact')),
                ('statut', models.CharField(blank=True, max_length=50, null=True, verbose_name='Statut')),
                ('date_validation', models.DateField(blank=True, null=True, verbose_name='Date de Validation')),
                ('n_tva', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de TVA')),
                ('iban', models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, null=True, verbose_name='BIC')),
                ('banque', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banque')),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('ID_collab', models.AutoField(primary_key=True, serialize=False)),
                ('ID_ESN', models.IntegerField()),
                ('Admin', models.BooleanField(default=False, verbose_name='Administrateur')),
                ('Commercial', models.BooleanField(default=False, verbose_name='Commercial')),
                ('Consultant', models.BooleanField(default=False, verbose_name='Consultant')),
                ('Actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('Nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('Prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('Date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de Naissance')),
                ('Poste', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poste')),
                ('date_debut_activ', models.DateField(blank=True, null=True, verbose_name="Date de Début d'Activité")),
                ('date_dé', models.DateField(blank=True, null=True, verbose_name='Date de Démission')),
                ('CV', models.URLField(blank=True, max_length=255, null=True, verbose_name='Lien CV')),
                ('LinkedIN', models.URLField(blank=True, max_length=255, null=True, verbose_name='Lien LinkedIn')),
                ('Mobilité', models.CharField(choices=[('National', 'National'), ('International', 'International'), ('Autres', 'Autres')], default='National', max_length=20, verbose_name='Mobilité')),
                ('Disponibilité', models.DateField(blank=True, null=True, verbose_name='Disponibilité')),
            ],
            options={
                'db_table': 'collaboration',
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id_contrat', models.AutoField(primary_key=True, serialize=False)),
                ('candidature_id', models.IntegerField()),
                ('numero_contrat', models.CharField(blank=True, max_length=50, null=True)),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('montant', models.FloatField()),
                ('statut', models.CharField(blank=True, max_length=20, null=True)),
                ('conditions', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contrat',
            },
        ),
        migrations.CreateModel(
            name='Doc_clt',
            fields=[
                ('ID_DOC_CLT', models.AutoField(primary_key=True, serialize=False)),
                ('ID_CLT', models.IntegerField()),
                ('Doc_URL', models.URLField(max_length=255, verbose_name='URL du Document')),
                ('Titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('Date_Valid', models.DateField(blank=True, null=True, verbose_name='Date de Validation')),
                ('Statut', models.CharField(max_length=50, verbose_name='Statut')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'doc_clt',
            },
        ),
        migrations.CreateModel(
            name='DocumentESN',
            fields=[
                ('ID_DOC_ESN', models.AutoField(primary_key=True, serialize=False)),
                ('ID_ESN', models.IntegerField()),
                ('Doc_URL', models.URLField(max_length=255, verbose_name='URL du Document')),
                ('Titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('Date_Valid', models.DateField(blank=True, null=True, verbose_name='Date de Validation')),
                ('Statut', models.CharField(max_length=50, verbose_name='Statut')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'doc_esn',
            },
        ),
        migrations.CreateModel(
            name='ESN',
            fields=[
                ('ID_ESN', models.AutoField(primary_key=True, serialize=False)),
                ('Raison_sociale', models.CharField(max_length=255, verbose_name='Raison Sociale')),
                ('SIRET', models.CharField(max_length=14, unique=True, verbose_name='Numéro SIRET')),
                ('RCE', models.CharField(blank=True, max_length=255, null=True, verbose_name='RCE')),
                ('Pays', models.CharField(max_length=100, verbose_name='Pays')),
                ('Adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('CP', models.CharField(max_length=10, verbose_name='Code Postal')),
                ('Ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('Province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Province')),
                ('mail_Contact', models.EmailField(max_length=191, unique=True, verbose_name='Email de Contact')),
                ('password', models.CharField(max_length=255, verbose_name='Mot de Passe')),
                ('Tel_Contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone de Contact')),
                ('Statut', models.CharField(blank=True, max_length=50, null=True, verbose_name='Statut')),
                ('Date_validation', models.DateField(blank=True, null=True, verbose_name='Date de Validation')),
                ('N_TVA', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de TVA')),
                ('IBAN', models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN')),
                ('BIC', models.CharField(blank=True, max_length=11, null=True, verbose_name='BIC')),
                ('Banque', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banque')),
            ],
            options={
                'db_table': 'esn',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('dest_id', models.IntegerField()),
                ('event_id', models.IntegerField()),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('categorie', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Partenariat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_client', models.IntegerField()),
                ('id_esn', models.IntegerField()),
                ('statut', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('categorie', models.CharField(choices=[('Diamond', 'Diamond'), ('Golden', 'Golden'), ('Silver', 'Silver')], max_length=10)),
            ],
            options={
                'db_table': 'partenariat',
            },
        ),
        migrations.CreateModel(
            name='Partenariat1',
            fields=[
                ('id_part', models.AutoField(primary_key=True, serialize=False)),
                ('id_client', models.IntegerField()),
                ('id_esn', models.IntegerField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('categorie', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'partenariat1',
            },
        ),
    ]
