# Generated by Django 5.1.2 on 2024-12-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maghrebIt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esn',
            name='Pays',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='esn',
            name='SIRET',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Numéro SIRET'),
        ),
        migrations.AlterField(
            model_name='esn',
            name='Ville',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='esn',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mot de Passe'),
        ),
    ]
