# Generated by Django 5.1.2 on 2024-12-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maghrebIt', '0002_alter_esn_pays_alter_esn_siret_alter_esn_ville_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentesn',
            name='Doc_URL',
            field=models.CharField(max_length=255, verbose_name='URL du Document'),
        ),
    ]
