# Generated by Django 5.1.2 on 2024-12-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maghrebIt', '0003_alter_documentesn_doc_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='img_path',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='img_path'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CP'),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mot de Passe'),
        ),
        migrations.AlterField(
            model_name='client',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='client',
            name='raison_sociale',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Raison Sociale'),
        ),
        migrations.AlterField(
            model_name='client',
            name='siret',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Numéro SIRET'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='doc_clt',
            name='Doc_URL',
            field=models.CharField(max_length=255, verbose_name='url path'),
        ),
    ]
