# Generated by Django 5.1.2 on 2025-01-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maghrebIt', '0004_client_img_path_alter_client_adresse_alter_client_cp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='token',
            field=models.TextField(blank=True, null=True, verbose_name='token'),
        ),
        migrations.AddField(
            model_name='esn',
            name='token',
            field=models.TextField(blank=True, null=True, verbose_name='token'),
        ),
    ]
